# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "ByggTeknikCentrum Tema"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "https://byggteknikcentrum.se"
tags = []
features = []
min_version = "0.38"

[author]
  name = "Jeremy Karlsson via Vufuzi"
  homepage = "https://vufuzi.se"
